<a href="https://colab.research.google.com/github/abubakarkhanlakhwera/GenAI/blob/main/pytorch/PyTorch_Training_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Work**

In [115]:
import numpy as np
import pandas as pd
import torch

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [116]:
df = pd.read_csv( 'https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [117]:
df.shape

(569, 33)

In [118]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [119]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

# **Train Test Split**

In [120]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

# **Scaling**

In [121]:
scaler  = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [122]:
X_train

array([[-0.44107853,  0.33296036, -0.42230201, ..., -0.09596883,
        -1.07780625,  0.0331853 ],
       [ 1.44588533, -0.26559428,  1.39646146, ...,  1.64151384,
         1.03667636, -0.35423237],
       [-1.2624792 ,  0.00352331, -1.27415349, ..., -1.18723519,
        -0.57243871, -0.28051771],
       ...,
       [ 1.04173502,  0.15896192,  0.87162406, ...,  0.02521566,
         3.03954405, -1.28314799],
       [-0.3240143 , -0.00343663, -0.40373084, ..., -1.60153468,
        -0.74761212, -1.18449228],
       [-0.09546033, -0.7226302 , -0.16513168, ..., -0.92820334,
        -0.86697807, -0.7277939 ]])

In [123]:
y_train

111    B
282    M
548    B
354    B
500    B
      ..
243    B
286    B
119    M
58     B
357    B
Name: diagnosis, Length: 455, dtype: object

# **Label Encoding**

In [124]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [125]:
y_train

array([0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,

# **Numpy arrays to PyTorch tensor**

In [126]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [127]:
X_train_tensor

tensor([[-0.4411,  0.3330, -0.4223,  ..., -0.0960, -1.0778,  0.0332],
        [ 1.4459, -0.2656,  1.3965,  ...,  1.6415,  1.0367, -0.3542],
        [-1.2625,  0.0035, -1.2742,  ..., -1.1872, -0.5724, -0.2805],
        ...,
        [ 1.0417,  0.1590,  0.8716,  ...,  0.0252,  3.0395, -1.2831],
        [-0.3240, -0.0034, -0.4037,  ..., -1.6015, -0.7476, -1.1845],
        [-0.0955, -0.7226, -0.1651,  ..., -0.9282, -0.8670, -0.7278]],
       dtype=torch.float64)

In [128]:
X_train_tensor.shape

torch.Size([455, 30])

In [129]:
y_train_tensor.shape

torch.Size([455])

# **Defining the model**

In [130]:
class MySimpleNN():
  def __init__(self,X):

    self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z = torch.matmul(X,self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self,y_pred,y):
    # Clamp prediction to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
    # Calculate Loss
    loss = -y*torch.log(y_pred) - (1-y)*torch.log(1-y_pred)
    return loss.mean()




# **Important Parameters**

In [131]:
learning_rate = 0.1
epochs = 25

# **Training Pipeline**

In [135]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epochs in range(epochs):
# forward pass
  y_pred = model.forward(X_train_tensor)


# loss calculator
  loss = model.loss_function(y_pred,y_train_tensor)
  # print(f'Epoch: {epochs+1}, Loss: {loss.item()}')
# backward pass
  loss.backward()

# parameter update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad
# zero gradient
  model.weights.grad.zero_()
  model.bias.grad.zero_()
# print loss in each epoch
  print(f'Epoch: {epochs+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.426803385395515
Epoch: 2, Loss: 3.2874297894598845
Epoch: 3, Loss: 3.1469896074384502
Epoch: 4, Loss: 3.000495622425435
Epoch: 5, Loss: 2.8519364285291195
Epoch: 6, Loss: 2.6992236706157056
Epoch: 7, Loss: 2.545358492714564
Epoch: 8, Loss: 2.38542673195272
Epoch: 9, Loss: 2.22640555225718
Epoch: 10, Loss: 2.0722743905736505
Epoch: 11, Loss: 1.9181519000153977
Epoch: 12, Loss: 1.7685558515972812
Epoch: 13, Loss: 1.625021120476527
Epoch: 14, Loss: 1.4946697665381026
Epoch: 15, Loss: 1.378094701696193
Epoch: 16, Loss: 1.2756989775302008
Epoch: 17, Loss: 1.1876178451938033
Epoch: 18, Loss: 1.113194120821066
Epoch: 19, Loss: 1.0508834635983668
Epoch: 20, Loss: 0.9988420754956457
Epoch: 21, Loss: 0.9553760811489539
Epoch: 22, Loss: 0.9190264521996623
Epoch: 23, Loss: 0.8885410328922496


In [136]:
model.weights

tensor([[-0.3224],
        [ 0.1363],
        [ 0.5718],
        [-0.2638],
        [ 0.1747],
        [ 0.0690],
        [-0.2595],
        [-0.3658],
        [ 0.3600],
        [ 0.0400],
        [ 0.3058],
        [ 0.4149],
        [-0.1313],
        [-0.2463],
        [ 0.0263],
        [-0.1207],
        [ 0.2737],
        [ 0.0277],
        [-0.0841],
        [-0.0367],
        [ 0.2247],
        [ 0.4509],
        [-0.0130],
        [-0.2009],
        [ 0.0323],
        [ 0.0593],
        [ 0.2436],
        [-0.3165],
        [ 0.4532],
        [ 0.2294]], dtype=torch.float64, requires_grad=True)

In [137]:
model.bias

tensor([-0.1270], dtype=torch.float64, requires_grad=True)

# **Model Evaluation**

In [152]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.99).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.6551246643066406
