<a href="https://colab.research.google.com/github/abubakarkhanlakhwera/GenAI/blob/main/pytorch/tensor_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1. Boring but useful
# 2. Knowledge of Deep learning
# 3. Very similar to NumPy
# 4. Lecture flow
# 5. Very close to PyTorch official documentation


# **What are tensors**

**vector,matrics and so on

1. Boring but useful
2. Knowledge of Deep learning
3. Very similar to NumPy
4. Lecture flow
5. Very close to PyTorch official documentation

 **What are tensors**

A tensor is a multi-dimensional array.  Think of it as a generalization of scalars, vectors, and matrices.

* Scalar: A single number (e.g., 5, 3.14).  A 0-dimensional tensor.
* Vector: An ordered sequence of numbers (e.g., [1, 2, 3]). A 1-dimensional tensor.
* Matrix: A 2-dimensional array of numbers (e.g., [[1, 2], [3, 4]]). A 2-dimensional tensor.
* Tensor:  An array with three or more dimensions. For example, a color image can be represented as a 3-dimensional tensor (height, width, color channels). A sequence of images forms a 4-dimensional tensor (time, height, width, color channels).

In PyTorch (and other deep learning frameworks), tensors are used to represent data, weights, and biases in neural networks.  They are optimized for efficient computations on GPUs and other hardware accelerators.  The core operations are similar to NumPy, but tensors can leverage hardware acceleration for significant performance gains.**

In [2]:
import torch
print(torch.__version__)

2.5.1+cu121


In [4]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Device name: {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available")

GPU is available
Device name: Tesla T4


# **Creating Tensor**

In [7]:
# by using empty

a = torch.empty(2,3)

In [9]:
# check type
type(a)

torch.Tensor

In [10]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [13]:
# using rand
# creat random tensor
torch.rand(2,3)

tensor([[0.1822, 0.1508, 0.9644],
        [0.4646, 0.6828, 0.3214]])

In [14]:
# manual seed
# fix random tensor
torch.manual_seed(100)
torch.rand(2,3)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [15]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [23]:
# using tensor
b = torch.tensor([[1,2,3],[4,5,6]])

In [25]:
b

tensor([[1, 2, 3],
        [4, 5, 6]])

In [27]:
# other ways
# arange
print('Using arange ->',torch.arange(0,10,2))
# Using linspace(linearly spaced)
print("Using linspace ->", torch.linspace(0,10,10))
# Using eye(Identity matrix)
print("Using eye ->", torch.eye(3))
# Using full(constant matrix)
# sytax torch.full((row,colum), entity))
print("Using full ->", torch.full((2,3), 5))

Using arange -> tensor([0, 2, 4, 6, 8])
Using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using eye -> tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
Using full -> tensor([[5, 5, 5],
        [5, 5, 5]])


# **Tensor Shapes**

In [28]:
x = torch.tensor([[1,2,3],[6,5,9]])

In [29]:
x

tensor([[1, 2, 3],
        [6, 5, 9]])

In [31]:
x.shape

torch.Size([2, 3])

In [32]:
torch.empty_like(x)
# What the code does:

# It takes the existing tensor x as input.
# It creates a new tensor with the same shape (dimensions), data type, and device as x.
# Important: The values inside the new tensor are not initialized; they will contain whatever data happens to be in the memory location allocated to the tensor.

tensor([[138134218271216, 138138008443824, 138138141834224],
        [138138141833392, 138138141827440, 138138141872176]])

In [33]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [34]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [35]:
# Intentional error
torch.rand_like(x)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

# **Tensor Data Types**

In [ ]:
# find data types

In [ ]:
# assign data type